# This file provides project-level configuration for the canon dev environment utility. https://github.com/viamrobotics/canon
periph_board:
    default: true
    image_amd64: ghcr.io/viamrobotics/antique2:amd64-cache
    image_arm64: ghcr.io/viamrobotics/antique2:arm64-cache
    image_arm: ghcr.io/viamrobotics/antique2:armhf-cache
    minimum_date: 2023-04-20T00:00:00.0Z
    update_interval: 168h0m0s
    user: testbot
    group: testbot
    persistent: true
